# Generated by Django 5.1.6 on 2025-05-03 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djezzy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='langues',
        ),
        migrations.AddField(
            model_name='candidat',
            name='photo_profil',
            field=models.ImageField(blank=True, default='profile_photos/default.jpg', null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='langue',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CandidatLangue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('A1', 'A1 - Débutant'), ('A2', 'A2 - Élémentaire'), ('B1', 'B1 - Intermédiaire'), ('B2', 'B2 - Intermédiaire supérieur'), ('C1', 'C1 - Avancé'), ('C2', 'C2 - Maîtrise')], max_length=2)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djezzy_app.candidat')),
                ('langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djezzy_app.langue')),
            ],
        ),
    ]
